name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - release
  pull_request:
    branches:
      - main
      - develop
      - release

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t chayathornl/go-hello-http:$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER .
          docker tag chayathornl/go-hello-http:$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER chayathornl/go-hello-http:latest
          docker images
            
      - name: Run Container and Execute tests
        run: |
          echo test
          docker run --name test-go-http-app -d -p 8080:8080 chayathornl/go-hello-http:latest
          docker run --name test-go-http-app-1 -d -p 8081:8080 chayathornl/go-hello-http:$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER
          curl http://localhost:8080
          echo '-----------------'
          curl http://localhost:8081

      - name: Push image to Docker Hub
        run: |
          docker images
          docker push chayathornl/go-hello-http:latest
          docker push chayathornl/go-hello-http:$GITHUB_REF_NAME-$GITHUB_RUN_NUMBER
          

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: ${{ needs.build.outputs.env_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Environment
        run: echo "Deploying to ${{ env.environment.name }} environment"
