name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - release
      # - 'feat/**'
  pull_request:
    branches:
      - main
      - develop
      - release

jobs:
  lint: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 
      - name: Set up Go 
        uses: actions/setup-go@v3 
        with: 
          go-version: '1.20'

      - name: Install dependencies for go app
        run: |
          go mod init example.com/main

      - name: Install golangci-lint and run
        run: | 
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
          export PATH=$PATH:$(go env GOPATH)/bin
          golangci-lint --version
          golangci-lint run ./...
        continue-on-error: true

  build:
    needs: lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t chayathornl/go-hello-http:1.0.$GITHUB_RUN_NUMBER .
          docker tag chayathornl/go-hello-http:1.0.$GITHUB_RUN_NUMBER chayathornl/go-hello-http:latest
          docker images
            
      - name: Run Container and Execute tests
        run: |
          echo test
          echo ${{ github.ref }}
          docker run --name test-go-http-app -d -p 8080:8080 chayathornl/go-hello-http:latest
          docker run --name test-go-http-app-1 -d -p 8081:8080 chayathornl/go-hello-http:1.0.$GITHUB_RUN_NUMBER
          curl http://localhost:8080
          echo '-----------------'
          curl http://localhost:8081

      - name: Push image to Docker Hub
        run: |
          docker images
          docker push chayathornl/go-hello-http:latest
          docker push chayathornl/go-hello-http:1.0.$GITHUB_RUN_NUMBER

  deploy_dev:
    if: github.event_name != 'pull_request'
    needs: [lint, build]
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check current branch
        run: |
          echo ${{ github.ref }}
      
      - name: Deploy on develop environment
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Deploy to develop"
          docker pull chayathornl/go-hello-http:latest
          docker run -p 8080:8080 -d chayathornl/go-hello-http:latest
          curl http://localhost:8080

  deploy_release:
    if: github.event_name != 'pull_request'
    needs: [lint, build]
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check current branch
        run: |
          echo ${{ github.ref }}
      
      - name: Deploy on release environment
        if: github.ref == 'refs/heads/release'
        run: |
          echo "Deploy to develop"
          docker pull chayathornl/go-hello-http:latest
          docker run -p 8080:8080 -d chayathornl/go-hello-http:latest
          curl http://localhost:8080

  deploy_prd:
    if: github.event_name != 'pull_request'
    needs: [lint, build]
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check current branch
        run: |
          echo ${{ github.ref }}
      
      - name: Deploy on prd environment
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploy to develop"
          docker pull chayathornl/go-hello-http:latest
          docker run -p 8080:8080 -d chayathornl/go-hello-http:latest
          curl http://localhost:8080



  # deploy:
  #   needs: build
  #   runs-on: ubuntu-24.04
  #   # environment:
  #   #   name: ${{ needs.build.outputs.env_name }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
      
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Check current branch
  #       run: |
  #         echo ${{ github.ref }}

  #     - name: Test before to merge
  #       if: startsWith(github.ref, '/feat/') || startsWith(github.ref, 'refs/pull')
  #       # run: echo "Deploying to ${{ env.environment.name }} environment"
  #       run: |
  #         echo "Deploy to develop"
  #         docker pull chayathornl/go-hello-http:latest
  #         docker run -p 8080:8080 -d chayathornl/go-hello-http:latest
  #         curl http://localhost:8080

  #     - name: Deploy to develop environment
  #       if: github.ref == 'refs/heads/develop'
  #       # run: echo "Deploying to ${{ env.environment.name }} environment"
  #       run: |
  #         echo "Deploy to develop"
  #         docker pull chayathornl/go-hello-http:latest
  #         docker run -p 8080:8080 -d chayathornl/go-hello-http:latest
  #         curl http://localhost:8080

  #     - name: Deploy to release environment
  #       if: github.ref == 'refs/heads/release'
  #       # run: echo "Deploying to ${{ env.environment.name }} environment"
  #       run: |
  #         echo "Deploy to develop"
  #         docker pull chayathornl/go-hello-http:latest
  #         docker run -p 8080:8080 -d chayathornl/go-hello-http:latest

  #         curl http://localhost:8080
  #     - name: Deploy to release environment
  #       if: github.ref == 'refs/heads/main'
  #       # run: echo "Deploying to ${{ env.environment.name }} environment"
  #       run: |
  #         echo "Deploy to develop"
  #         docker pull chayathornl/go-hello-http:latest
  #         docker run -p 8080:8080 -d chayathornl/go-hello-http:latest
  #         curl http://localhost:8080
