name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - release
  pull_request:
    branches:
      - main
      - develop
      - release
  workflow_dispatch:
    inputs:
      version:
        description: 'Deployment version' 
        required: true 
        default: '1.0.0'

jobs:
  scan: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 
      - name: Set up Go 
        uses: actions/setup-go@v3 
        with: 
          go-version: '1.20'

      - name: Install dependencies for go app
        run: |
          go mod init example.com/main

      - name: Install golangci-lint and run
        run: | 
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
          export PATH=$PATH:$(go env GOPATH)/bin
          golangci-lint --version
          golangci-lint run ./...
        continue-on-error: true

  build:
    needs: scan
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t chayathornl/go-hello-http:1.0.$GITHUB_RUN_NUMBER .
          docker tag chayathornl/go-hello-http:1.0.$GITHUB_RUN_NUMBER chayathornl/go-hello-http:latest
          docker images
            
      - name: Run Container and Execute tests
        run: |
          echo test
          echo ${{ github.ref }}
          docker run --name test-go-http-app -d -p 8080:8080 chayathornl/go-hello-http:latest
          docker run --name test-go-http-app-1 -d -p 8081:8080 chayathornl/go-hello-http:1.0.$GITHUB_RUN_NUMBER
          curl http://localhost:8080
          echo '-----------------'
          curl http://localhost:8081

      - name: Push image to Docker Hub
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/release' || github.ref == 'refs/heads/main') && github.event_name == 'workflow_dispatch'
        run: |
          docker images
          docker push chayathornl/go-hello-http:latest
          docker push chayathornl/go-hello-http:1.0.$GITHUB_RUN_NUMBER
          echo 'Push image version: 1.0.$GITHUB_RUN_NUMBER'

  deploy_dev:
    if: github.event_name != 'pull_request' || github.event_name == 'workflow_dispatch'
    needs: [scan, build]
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check current branch
        run: |
          echo ${{ github.ref }}
      
      - name: Deploy on develop environment
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "Deploy to develop"
          docker pull chayathornl/go-hello-http:latest
          docker run -p 8080:8080 -d chayathornl/go-hello-http:latest
          curl http://localhost:8080

  deploy_release:
    if: github.event_name != 'pull_request' || github.event_name == 'workflow_dispatch'
    needs: [scan, build]
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check current branch
        run: |
          echo ${{ github.ref }}
      
      - name: Deploy on release environment
        if: github.ref == 'refs/heads/release' && github.event_name == 'workflow_dispatch'
        run: |
          echo "Deploy to release environment"
          docker pull chayathornl/go-hello-http:$version
          docker run -p 8080:8080 -d chayathornl/go-hello-http:$version
          curl http://localhost:8080

  deploy_prd:
    if: github.event_name != 'pull_request' || github.event_name == 'workflow_dispatch'
    needs: [scan, build]
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check current branch
        run: |
          echo ${{ github.ref }}
      
      - name: Deploy on prd environment
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: |
          echo "Deploy to prd"
          docker pull chayathornl/go-hello-http:$version
          docker run -p 8080:8080 -d chayathornl/go-hello-http:$version
          curl http://localhost:8080
